### PR TITLE
add prior year materials

### PR DESCRIPTION
**Pull request by matchings**
adding notebooks from past years for Visual Behavior Ophys, Visual Coding Ophys, and Visual Coding Neuropixels.

Visual Behavior Ophys Exercises notebook has been modified to work with brain_observatory_utilities instead of mindscope_utilities

Visual Coding Ophys solutions notebook is confirmed to run, but it is very slow for some reason 

Visual Coding Neuropixels notebooks have an error early on when trying to load the cache. We need to track down what about the SDK has changed to cause this and/or what needs to be updated to get it to run properly.

### CODE REVIEW

**Comment by matchings** [comment]
@egmcbride @jsiegle @corbennett  The Visual Coding Neuropixels notebooks from SWDB 2019 are giving an error when trying to load the EcephysProjectCache - any idea why this is happening? Maybe something about the SDK has changed since last year's workshop? any help here would be much appreciated. 

here is the error: 

image

**Comment by jsiegle** [comment]
Can you try running:

```python
cache = EcephysProjectCache.from_warehouse(manifest=manifest_path)
```
instead?

**Comment by matchings** [comment]
@jsiegle That worked! Thanks for the quick response. 

Unfortunately I am getting additional errors later down the notebook that make me think that enough has changed about the SDK since this notebook was created that it will take some time to work through all the changes. 

Here's an example of what I mean - the notebook uses `structure_acronyms` but it appears that the current / correct column name is `ecephys_structure_acronyms`. I think its going to take working through the whole notebook to fully update. I can work on that in the next few days. In the mean time, we can refer people to the tutorials on the website, instead of the SWDB notebooks. I assume those are up to date and functional with current SDK. 

image

**Comment by jsiegle** [comment]
The convention of using `ecephys_structure_acronyms` for the Visual Coding data hasn't changed in a while (definitely not since last year). If you just do a Find & Replace on `structure_acronyms`, it should fix that issue, at least.

**Comment by matchings** [comment]
Maybe I got an outdated version of the tutorial somehow…

**Pull request merged**
